### ISSUE TITLE
Extra Accidental on multi-voice Chord

### ISSUE THREAD

**Issue by arshiacont** [grame-cncm/guidolib#147]
An accidental on the same note but two voices, should not be graphically repeated. As is the case here:
```
{[ \staff<1> \clef<"g2"> \stemsUp a#1/16 ], 
[ \staff<1>  \stemsDown  a#1/16 ]}
```

But when in a chord, it is repeated:
```
{[ \staff<1> \clef<"g2"> \stemsUp { a#1/16,  e2/16}  ], 
[ \staff<1>  \stemsDown  a#1/16 ]}
```

![image](https://user-images.githubusercontent.com/3298204/159118802-e1b0f5bd-98c8-48e1-82ed-442f983b921e.png)

**Comment by dfober** [comment]
fixed
Note that it change #145 rendering: to get the same result, the first accidental has to be forced (i.e. \acc(a#1/16)) otherwise none prevails.

**Comment by arshiacont** [comment]
Thanks! Makes total sense.

Could you please update the Grame's online GuidoEditor with the Head of Dev branch? I am still seeing the issue on my side and am wondering whether I'm doing anything wrong... .

**Comment by dfober** [comment]
That's done.
